Traceback (most recent call last):
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/jfoley19/miniforge3/envs/jbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import psi4

import psi4
import numpy as np

# set molecule
mol = psi4.geometry("""
h
h 1 x
symmetry c1
""")   

# set some options for psi4
psi4.set_options({'basis': 'cc-pvdz',
                  'guess_mix': True,
                  'reference': 'rhf'})

# tell psi4 not to print any output to the screen
psi4.core.be_quiet()

# calculate the energy at different H-H separations, x
hf_energy = []
ci_energy = []
mp2_energy = []
mp3_energy = []
mp4_energy = []
dx = 0.1
x = np.arange(0.3, 8.1, dx)
for i in range (0, len(x)):
    mol.x = x[i]
    
    # full ci
    en = psi4.energy('fci')
    ci_energy.append(en)

    # hartree-fock and MPn
    en = psi4.energy('mp4')
    ehf = psi4.variable("HF TOTAL ENERGY")
    hf_energy.append(ehf)
    mp2_energy.append(ehf + psi4.variable("MP2 CORRELATION ENERGY"))
    mp3_energy.append(ehf + psi4.variable("MP3 CORRELATION ENERGY"))
    mp4_energy.append(ehf + psi4.variable("MP4 CORRELATION ENERGY"))
    
------------------


[31m---------------------------------------------------------------------------[39m
[31mImportError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpsi4[39;00m
[32m      3[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mpsi4[39;00m
[32m      4[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mnp[39;00m

[36mFile [39m[32m~/Code/psi4/objdir-Release/stage/lib/psi4/__init__.py:71[39m
[32m     68[39m data_dir = [38;5;28mstr[39m(data_dir)
[32m     70[39m [38;5;66;03m# Init core[39;00m
[32m---> [39m[32m71[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01m.[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m core
[32m     73[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mpsi4[39;00m[34;01m.[39;00m[34;01mcore[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m get_num_threads, set_num_threads
[32m     74[39m core.initialize()

[31mImportError[39m: cannot import name 'core' from partially initialized module 'psi4' (most likely due to a circular import) (/Users/jfoley19/Code/psi4/objdir-Release/stage/lib/psi4/__init__.py)

